import type { Metadata } from "next";
import "./globals.css";
import ClientOnly from "@/components/common/ClientOnly";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "هومسا |‌رزور و اجاره ویلا در سراسر کشور | پشتیبانی ۲۴ ساعته",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body suppressHydrationWarning={true} className="bg-whiteColor text-blackColor">
        <ClientOnly>
          <Navbar />
        </ClientOnly>
        {children}
        <ClientOnly>
          <Footer />
        </ClientOnly>
      </body>
    </html>
  );
}
